name: Testando build da imagem Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building da image Docker do Simple-Chat
      run: docker build . --file Dockerfile --tag simple-chat:ci
      
  logs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: logs do container
    - run: docker run simple-chat list
      
  
      
